/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.JPanels;
import Controllers.ClientsController;
import Models.EntitiesManagers.Manager;
import Models.Entities.Client;
import Models.EntitiesManagers.ClientManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author mawena
 */
public class ClientsOld extends javax.swing.JPanel {

    /**
     * Creates new form ClientManagementBase2
     */
    public ClientsOld() {
        initComponents();
        Manager.connect();
        clientTable.setModel(ClientManager.toTableModel(ClientManager.getAll()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        clientSearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        clientCNI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addClientButton = new javax.swing.JButton();
        updateClientButton = new javax.swing.JButton();
        delClientButton = new javax.swing.JButton();
        clientCategory = new javax.swing.JComboBox<>();
        clientTel = new javax.swing.JTextField();
        clientFirstName = new javax.swing.JTextField();
        clientLastName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientTable = new javax.swing.JTable();
        clearButton = new javax.swing.JButton();
        refrechButton = new javax.swing.JButton();

        jLabel6.setText("Gestion des clients");

        clientSearch.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                clientSearchInputMethodTextChanged(evt);
            }
        });
        clientSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientSearchActionPerformed(evt);
            }
        });
        clientSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clientSearchKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clientSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                clientSearchKeyReleased(evt);
            }
        });

        jLabel7.setText("Rechercher");

        clientCNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientCNIActionPerformed(evt);
            }
        });

        jLabel1.setText("CNI");

        jLabel2.setText("Nom");

        jLabel3.setText("Prénom");

        jLabel4.setText("Tel");

        jLabel5.setText("Catégorie");

        addClientButton.setText("Ajouter");
        addClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientButtonActionPerformed(evt);
            }
        });

        updateClientButton.setText("Modifier");
        updateClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateClientButtonActionPerformed(evt);
            }
        });

        delClientButton.setText("Suprimmer");
        delClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delClientButtonActionPerformed(evt);
            }
        });

        clientCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "detaillant", "grossiste" }));

        clientTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientTelActionPerformed(evt);
            }
        });

        clientLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientLastNameActionPerformed(evt);
            }
        });

        clientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CNI", "Nom", "Prénoms", "Tel", "Catégorie"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clientTable);

        clearButton.setText("Effacer");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        refrechButton.setText("Recharger");
        refrechButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrechButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateClientButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delClientButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clientLastName)
                            .addComponent(clientCNI)
                            .addComponent(clientCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientFirstName)
                            .addComponent(clientTel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addComponent(clientSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(refrechButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(clientCNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clientSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(refrechButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(clientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(clientTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(clientCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addClientButton)
                            .addComponent(updateClientButton)
                            .addComponent(delClientButton)
                            .addComponent(clearButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clientSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientSearchActionPerformed

    private void clientSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientSearchKeyPressed
        //
    }//GEN-LAST:event_clientSearchKeyPressed

    private void clientCNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientCNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientCNIActionPerformed

    private void addClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClientButtonActionPerformed
        if(ClientsController.store(new Client(clientCNI.getText(), clientLastName.getText(), clientFirstName.getText(), clientCategory.getSelectedItem().toString(), clientTel.getText(), "H"))){
            clientCNI.setText("");
            clientLastName.setText("");
            clientFirstName.setText("");
            clientTel.setText("");
        }
        clientTable.setModel(ClientManager.toTableModel(ClientManager.getAll()));
        
    }//GEN-LAST:event_addClientButtonActionPerformed

    private void clientTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientTelActionPerformed

    private void clientLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientLastNameActionPerformed

    private void clientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) clientTable.getModel();
        int myIndex = clientTable.getSelectedRow();
        clientCNI.setText(model.getValueAt(myIndex, 1).toString());
        clientLastName.setText(model.getValueAt(myIndex, 2).toString());
        clientFirstName.setText(model.getValueAt(myIndex, 3).toString());
        clientTel.setText(model.getValueAt(myIndex, 4).toString());
        clientCategory.setSelectedItem(model.getValueAt(myIndex, 5).toString());
    }//GEN-LAST:event_clientTableMouseClicked

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clientCNI.setText("");
        clientLastName.setText("");
        clientFirstName.setText("");
        clientTel.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void delClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delClientButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) clientTable.getModel();
        int myIndex = clientTable.getSelectedRow();
        ClientsController.destroy(Integer.parseInt(model.getValueAt(myIndex, 0).toString()));
        clientTable.setModel(ClientManager.toTableModel(ClientManager.getAll()));
    }//GEN-LAST:event_delClientButtonActionPerformed

    private void updateClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateClientButtonActionPerformed
        
    }//GEN-LAST:event_updateClientButtonActionPerformed

    private void refrechButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrechButtonActionPerformed
        clientSearch.setText("");
        clientTable.setModel(ClientManager.toTableModel(ClientManager.getAll()));
    }//GEN-LAST:event_refrechButtonActionPerformed

    private void clientSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientSearchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_clientSearchKeyTyped

    private void clientSearchInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_clientSearchInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_clientSearchInputMethodTextChanged

    private void clientSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientSearchKeyReleased
        clientTable.setModel(ClientManager.toTableModel(ClientManager.search("last_name", clientSearch.getText())));
    }//GEN-LAST:event_clientSearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClientButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField clientCNI;
    private javax.swing.JComboBox<String> clientCategory;
    private javax.swing.JTextField clientFirstName;
    private javax.swing.JTextField clientLastName;
    private javax.swing.JTextField clientSearch;
    private javax.swing.JTable clientTable;
    private javax.swing.JTextField clientTel;
    private javax.swing.JButton delClientButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refrechButton;
    private javax.swing.JButton updateClientButton;
    // End of variables declaration//GEN-END:variables
}
