/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.JPanels;

import Main.Main;

/**
 *
 * @author mawena
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginContainerPanel = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        usernameLabel = new javax.swing.JLabel();
        usernameJText = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordJText = new javax.swing.JPasswordField();
        connexionButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        illustrationLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        loginContainerPanel.setBackground(new java.awt.Color(34, 67, 128));
        loginContainerPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        loginLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/login-min.png"))); // NOI18N
        loginLabel.setText("Connexion");

        typeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/people-min.png"))); // NOI18N

        typeComboBox.setBackground(new java.awt.Color(34, 67, 128));
        typeComboBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        typeComboBox.setForeground(new java.awt.Color(255, 255, 255));
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerant", "Comptable" }));
        typeComboBox.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        usernameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/user-min-2.png"))); // NOI18N

        usernameJText.setBackground(new java.awt.Color(34, 67, 128));
        usernameJText.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        usernameJText.setForeground(new java.awt.Color(255, 255, 255));
        usernameJText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameJText.setText("mawena");
        usernameJText.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nom d'utilisateur", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        usernameJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameJTextActionPerformed(evt);
            }
        });

        passwordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/padlock-min.png"))); // NOI18N

        passwordJText.setBackground(typeComboBox.getBackground());
        passwordJText.setForeground(new java.awt.Color(255, 255, 255));
        passwordJText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordJText.setText("licdovic");
        passwordJText.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mot de passe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        connexionButton.setBackground(new java.awt.Color(34, 67, 128));
        connexionButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        connexionButton.setForeground(new java.awt.Color(254, 254, 254));
        connexionButton.setText("SE CONNECTER");
        connexionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connexionButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/repair-shop-min.png"))); // NOI18N

        javax.swing.GroupLayout loginContainerPanelLayout = new javax.swing.GroupLayout(loginContainerPanel);
        loginContainerPanel.setLayout(loginContainerPanelLayout);
        loginContainerPanelLayout.setHorizontalGroup(
            loginContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContainerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginContainerPanelLayout.createSequentialGroup()
                        .addGroup(loginContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeLabel)
                            .addComponent(passwordLabel)
                            .addComponent(usernameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(loginContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginContainerPanelLayout.createSequentialGroup()
                                .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(loginContainerPanelLayout.createSequentialGroup()
                                .addGroup(loginContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameJText, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(passwordJText)
                                    .addComponent(typeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginContainerPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(183, 183, 183))
                    .addGroup(loginContainerPanelLayout.createSequentialGroup()
                        .addComponent(connexionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        loginContainerPanelLayout.setVerticalGroup(
            loginContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContainerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(loginLabel)
                .addGap(18, 18, 18)
                .addGroup(loginContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginContainerPanelLayout.createSequentialGroup()
                        .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameJText, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginContainerPanelLayout.createSequentialGroup()
                        .addComponent(typeLabel)
                        .addGap(33, 33, 33)
                        .addComponent(usernameLabel)
                        .addGap(29, 29, 29)))
                .addGroup(loginContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordJText, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginContainerPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(connexionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        illustrationLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/Secure login.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginContainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(illustrationLabel)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loginContainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(illustrationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usernameJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameJTextActionPerformed

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void connexionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connexionButtonActionPerformed
        // TODO add your handling code here:
        Main.connectUser(usernameJText.getText(), passwordJText.getText(), typeComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_connexionButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connexionButton;
    private javax.swing.JLabel illustrationLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel loginContainerPanel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPasswordField passwordJText;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JTextField usernameJText;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
