/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.JPanels;

import Main.Main;
import java.awt.CardLayout;

/**
 *
 * @author mawena
 */
public class MainPanel extends javax.swing.JPanel {

    private static CardLayout card = new CardLayout();
    private static StockPanel stockPanel = null;
    
    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        stockPanel = new StockPanel();
        cardPanel.setLayout(card);
        cardPanel.add(stockPanel, "1");
        card.show(cardPanel, "1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();
        disconnectButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        commandButton = new javax.swing.JButton();
        billButton = new javax.swing.JButton();
        productButton = new javax.swing.JButton();
        stockButton = new javax.swing.JButton();
        clientButton = new javax.swing.JButton();
        personnelButton = new javax.swing.JButton();
        utilisateurButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(34, 67, 128));

        cardPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout cardPanelLayout = new javax.swing.GroupLayout(cardPanel);
        cardPanel.setLayout(cardPanelLayout);
        cardPanelLayout.setHorizontalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        cardPanelLayout.setVerticalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        disconnectButton.setBackground(new java.awt.Color(34, 67, 128));
        disconnectButton.setForeground(new java.awt.Color(255, 255, 255));
        disconnectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/logout-min.png"))); // NOI18N
        disconnectButton.setText("Deconnexion");
        disconnectButton.setBorder(null);
        disconnectButton.setBorderPainted(false);
        disconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectButtonActionPerformed(evt);
            }
        });

        closeButton.setBackground(new java.awt.Color(34, 67, 128));
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/closer-min.png"))); // NOI18N
        closeButton.setBorder(null);
        closeButton.setBorderPainted(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        commandButton.setBackground(new java.awt.Color(34, 67, 128));
        commandButton.setForeground(new java.awt.Color(255, 255, 255));
        commandButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/order-delivery-min.png"))); // NOI18N
        commandButton.setText("Commandes");
        commandButton.setBorder(null);
        commandButton.setBorderPainted(false);
        commandButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        commandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commandButtonActionPerformed(evt);
            }
        });

        billButton.setBackground(new java.awt.Color(34, 67, 128));
        billButton.setForeground(new java.awt.Color(255, 255, 255));
        billButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/bill-min.png"))); // NOI18N
        billButton.setText("Factures");
        billButton.setBorder(null);
        billButton.setBorderPainted(false);
        billButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        billButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billButtonActionPerformed(evt);
            }
        });

        productButton.setBackground(new java.awt.Color(34, 67, 128));
        productButton.setForeground(new java.awt.Color(255, 255, 255));
        productButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/product.png"))); // NOI18N
        productButton.setText("Produits");
        productButton.setBorder(null);
        productButton.setBorderPainted(false);
        productButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        productButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productButtonActionPerformed(evt);
            }
        });

        stockButton.setBackground(new java.awt.Color(34, 67, 128));
        stockButton.setForeground(new java.awt.Color(255, 255, 255));
        stockButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/stock.png"))); // NOI18N
        stockButton.setText("Stock");
        stockButton.setBorder(null);
        stockButton.setBorderPainted(false);
        stockButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockButtonActionPerformed(evt);
            }
        });

        clientButton.setBackground(new java.awt.Color(34, 67, 128));
        clientButton.setForeground(new java.awt.Color(255, 255, 255));
        clientButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/client.png"))); // NOI18N
        clientButton.setText("Client");
        clientButton.setBorder(null);
        clientButton.setBorderPainted(false);
        clientButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientButtonActionPerformed(evt);
            }
        });

        personnelButton.setBackground(new java.awt.Color(34, 67, 128));
        personnelButton.setForeground(new java.awt.Color(255, 255, 255));
        personnelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/personnel.png"))); // NOI18N
        personnelButton.setText("Personnel");
        personnelButton.setBorder(null);
        personnelButton.setBorderPainted(false);
        personnelButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        personnelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personnelButtonActionPerformed(evt);
            }
        });

        utilisateurButton.setBackground(new java.awt.Color(34, 67, 128));
        utilisateurButton.setForeground(new java.awt.Color(255, 255, 255));
        utilisateurButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/personnel.png"))); // NOI18N
        utilisateurButton.setText("Utilisateurs");
        utilisateurButton.setBorder(null);
        utilisateurButton.setBorderPainted(false);
        utilisateurButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        utilisateurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilisateurButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commandButton, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(billButton, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(productButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(personnelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(stockButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(clientButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(utilisateurButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(disconnectButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeButton))
                    .addComponent(cardPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(commandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(billButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(productButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(stockButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(personnelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(utilisateurButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(closeButton)
                            .addComponent(disconnectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void commandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commandButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commandButtonActionPerformed

    private void disconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectButtonActionPerformed
        // TODO add your handling code here:
        Main.disconnectUser();
    }//GEN-LAST:event_disconnectButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        Main.close();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void billButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billButtonActionPerformed

    private void productButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productButtonActionPerformed

    private void personnelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personnelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personnelButtonActionPerformed

    private void stockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockButtonActionPerformed

    private void clientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientButtonActionPerformed

    private void utilisateurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilisateurButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utilisateurButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billButton;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JButton clientButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton commandButton;
    private javax.swing.JButton disconnectButton;
    private javax.swing.JButton personnelButton;
    private javax.swing.JButton productButton;
    private javax.swing.JButton stockButton;
    private javax.swing.JButton utilisateurButton;
    // End of variables declaration//GEN-END:variables
}
