/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.JFrames;

import Model.entitiesManagers.Manager;
import javax.swing.JFrame;
import javax.swing.JPanel;
import View.JPanels.Clients;
import View.JPanels.Products;
import View.JPanels.Users;
import java.awt.CardLayout;

/**
 *
 * @author mawena
 */
public class ActivityFrame extends JFrame {

    /**
     * Creates new form ActivityFrame
     */
    
    public JPanel clients = new Clients();
    public JPanel produits = new Products();
    public JPanel users = new Users();
    public CardLayout card = new CardLayout();
    public ActivityFrame() {
        initComponents();
        Manager.connect();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        bodyCardLayout.setLayout(card);
        bodyCardLayout.add(clients, "1");
        bodyCardLayout.add(produits, "2");
        bodyCardLayout.add(users, "5");
        card.show(bodyCardLayout, "1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        navBar = new javax.swing.JPanel();
        navClientsButton1 = new javax.swing.JButton();
        navProductsButton1 = new javax.swing.JButton();
        navOrdersButton1 = new javax.swing.JButton();
        navUsersButton1 = new javax.swing.JButton();
        navEmployersButton2 = new javax.swing.JButton();
        bodyCardLayout = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("container");

        navBar.setBackground(new java.awt.Color(88, 112, 223));

        navClientsButton1.setBackground(java.awt.SystemColor.window);
        navClientsButton1.setFont(new java.awt.Font("Liberation Serif", 1, 36)); // NOI18N
        navClientsButton1.setText("Clients");
        navClientsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navClientsButton1ActionPerformed(evt);
            }
        });

        navProductsButton1.setBackground(navClientsButton1.getBackground());
        navProductsButton1.setFont(navClientsButton1.getFont());
        navProductsButton1.setForeground(navClientsButton1.getForeground());
        navProductsButton1.setText("Produits");
        navProductsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navProductsButton1ActionPerformed(evt);
            }
        });

        navOrdersButton1.setBackground(navClientsButton1.getBackground());
        navOrdersButton1.setFont(navClientsButton1.getFont());
        navOrdersButton1.setForeground(navClientsButton1.getForeground());
        navOrdersButton1.setText("Commandes");
        navOrdersButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navOrdersButton1ActionPerformed(evt);
            }
        });

        navUsersButton1.setBackground(navClientsButton1.getBackground());
        navUsersButton1.setFont(navClientsButton1.getFont());
        navUsersButton1.setForeground(navClientsButton1.getForeground());
        navUsersButton1.setText("Utilisateurs");
        navUsersButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navUsersButton1ActionPerformed(evt);
            }
        });

        navEmployersButton2.setBackground(navClientsButton1.getBackground());
        navEmployersButton2.setFont(navClientsButton1.getFont());
        navEmployersButton2.setForeground(navClientsButton1.getForeground());
        navEmployersButton2.setText("Employers");
        navEmployersButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navEmployersButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navBarLayout = new javax.swing.GroupLayout(navBar);
        navBar.setLayout(navBarLayout);
        navBarLayout.setHorizontalGroup(
            navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navProductsButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(navClientsButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(navUsersButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(navOrdersButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(navEmployersButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        navBarLayout.setVerticalGroup(
            navBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navClientsButton1)
                .addGap(40, 40, 40)
                .addComponent(navEmployersButton2)
                .addGap(40, 40, 40)
                .addComponent(navProductsButton1)
                .addGap(40, 40, 40)
                .addComponent(navOrdersButton1)
                .addGap(40, 40, 40)
                .addComponent(navUsersButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        bodyCardLayout.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addComponent(navBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyCardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navClientsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navClientsButton1ActionPerformed
        card.show(bodyCardLayout, "1");
    }//GEN-LAST:event_navClientsButton1ActionPerformed

    private void navProductsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navProductsButton1ActionPerformed
        card.show(bodyCardLayout, "2");
    }//GEN-LAST:event_navProductsButton1ActionPerformed

    private void navOrdersButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navOrdersButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navOrdersButton1ActionPerformed

    private void navUsersButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navUsersButton1ActionPerformed
        card.show(bodyCardLayout, "5");
    }//GEN-LAST:event_navUsersButton1ActionPerformed

    private void navEmployersButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navEmployersButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navEmployersButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActivityFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActivityFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActivityFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActivityFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActivityFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyCardLayout;
    private javax.swing.JPanel container;
    private javax.swing.JPanel navBar;
    private javax.swing.JButton navClientsButton1;
    private javax.swing.JButton navEmployersButton2;
    private javax.swing.JButton navOrdersButton1;
    private javax.swing.JButton navProductsButton1;
    private javax.swing.JButton navUsersButton1;
    // End of variables declaration//GEN-END:variables
}
